typography_spectrum: 0.25029
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.460501509020105
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99626
analytics:
  google: null
  facebook: null
  twitter: null
name: PUBLIC FILMS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GHOST SOUTH ROAD
description: A Documentary Artwork
purpose: []
