typography_spectrum: 0.22982
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.460501509020105
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Ghost South Road
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook Feed
    url: 'https://www.facebook.com/greatsouthroadfragments/'
    type: external
favicon: null
title: GHOST SOUTH ROAD
description: ''
purpose: []
