name: Fragments of the Great South Road
favicon: null
layout_spectrum: 0.99626
typography_spectrum: 0.25029
title: DOCUMENTARY ARTWORK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.460501509020105
  rhythmicContrast: 0.5
purpose: []
